<?php
/**
 * Copyright © 2016 Oceanpayment Design. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \Oceanpayment\FPS\Block\Info
 */
?>
<?php echo $this->escapeHtml($block->getMethod()->getTitle()) ?>
    {{pdf_row_separator}}
<?php echo __('FPS Transaction ID: %1', $this->escapeHtml($block->getInfo()->getLastTransId())) ?>
    {{pdf_row_separator}}
