<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
    <div class="loader">
        <img src="<?php echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
             alt="<?php echo __('Loading...'); ?>"
             style="position: absolute;">
    </div>
</div>

<div>
<?php echo $block->getCheckoutForm(); ?>

<p style="font: 16px; padding: 0px; text-align: center; margin: 100px auto 0px; width: 90%;"><?php echo __('Processing, please do not click the refresh button.'); ?></p>
<script type="text/javascript">
	document.payment_checkout.submit();
</script>

</div>